### ISSUE TITLE
Rewrite worker to be a RabbitMQ consumer.

### ISSUE THREAD

**Issue by GoldenBadger** [CPSSD/heracles#375]
- [x] Add broker interface to worker (#384)
- [x] Save data to state store instead of to the master (#396 )
- [ ] Add an adapter to old code (#387)
