### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by VoyTechnology** [CPSSD/heracles#415]
Final code cleanup. This is composed of:

- [x] Removing old worker (#412)
- [x] Removing old CLI (#413)
- [x] Removing old protobufs (#416)
- [ ] Updating documentations
- [ ] Finalizing Deployment files
- [ ] Renaming any remaining parts from cerberus to heracles.
